add support for socket activation
twosigma/nsncd pull request #111
Opened 2024-04-29 11:08 UTC by flokli

If nsncd is started using socket activation, use the passed FD instead of manually binding on SOCKET_PATH.

2024-04-29 22:28 UTC, blinsay requested changes
Looks good, some comments in line. Have you tested it locally with socket activation yet?

2024-04-29 22:28 UTC, blinsay commented on src/main.rs
> +        .expect("invalid socket type at index")
I think it makes slightly more sense to log an error and exit here but I don't feel strongly about it.

2024-04-29 22:28 UTC, blinsay commented on src/main.rs
> +            let path = Path::new(SOCKET_PATH);
let's throw this in a `fn`

2024-05-08 11:46 UTC, flokli commented
> Looks good, some comments in line. Have you tested it locally with socket activation yet?

I did check it actually starting up, via `systemd-socket-activate`:

```
❯ systemd-socket-activate -l /tmp/foobar.sock target/debug/nsncd
Listening on /tmp/foobar.sock as 3.
Communication attempt on fd 3.
Execing target/debug/nsncd (target/debug/nsncd)
```

I wrote some spam to it, pointing curl to it, and (successfully) got back an error about the wrong protocol version:

```
May 08 11:43:02.917 DEBG accepted connection, stream: UnixStream { fd: FileDesc(OwnedFd { fd: 4 }), local: "/tmp/foobar.sock" (pathname), peer: (unnamed) }, thread: worker_2
May 08 11:43:02.917 DEBG parsing request, err: wrong protocol version 542393671, thread: worker_2
```

I have some systemd config to wire it up there, but I ran into some unrelated other issues and didn't get to fully test it yet. I will, happy to mark it as draft until then.

2024-06-29 07:57 UTC, flokli commented
Shelving these efforts for now, let's revisit this once https://github.com/systemd/systemd/pull/30360 has landed in a release, as it'd probably be revisited after that anyways.

2024-06-29 07:57 UTC, closed without merging